from time import sleep as s
from pynput import mouse
from pynput.mouse import Button
from pynput import keyboard
from pynput.keyboard import Key

keyboard = keyboard.Controller()
mouse = mouse.Controller()

s(5)

# Restart game
mouse.position = (957, 914)
s(0.1)
mouse.press(Button.left)
mouse.release(Button.left)
s(2)
mouse.position = (706, 855)
s(0.1)
mouse.press(Button.left)
mouse.release(Button.left)
s(2)
mouse.position = (838, 930)
s(0.1)
mouse.press(Button.left)
mouse.release(Button.left)
s(2)
mouse.position = (821, 980)
s(0.1)
mouse.press(Button.left)
mouse.release(Button.left)
s(1)
mouse.position = (275, 430)
s(0.1)
mouse.press(Button.left)
mouse.release(Button.left)
s(1)
mouse.position = (535, 251)
s(0.1)
mouse.press(Button.left)
mouse.release(Button.left)
s(1)
mouse.position = (634, 418)
s(0.1)
mouse.press(Button.left)
mouse.release(Button.left)
s(1)
mouse.position = (1282, 455)
s(0.1)
mouse.press(Button.left)
mouse.release(Button.left)
s(5)
mouse.position = (972, 766)
s(0.1)
mouse.press(Button.left)
mouse.release(Button.left)
s(1)